#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-modest
Version  : 0.3.1
Release  : 35
URL      : https://cran.r-project.org/src/contrib/modest_0.3-1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/modest_0.3-1.tar.gz
Summary  : Model-Based Dose-Escalation Trials
Group    : Development/Tools
License  : GPL-2.0
Requires: R-knitr
Requires: R-rhandsontable
Requires: R-shiny
Requires: R-shinyBS
BuildRequires : R-knitr
BuildRequires : R-rhandsontable
BuildRequires : R-shiny
BuildRequires : R-shinyBS
BuildRequires : buildreq-R

%description
No detailed description available

%prep
%setup -q -c -n modest
cd %{_builddir}/modest

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641063168

%install
export SOURCE_DATE_EPOCH=1641063168
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library modest
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library modest
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library modest
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc modest || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/modest/CITATION
/usr/lib64/R/library/modest/Conduct/ConductReport.Rnw
/usr/lib64/R/library/modest/Conduct/app.R
/usr/lib64/R/library/modest/Conduct/mainDoseEscalation.R
/usr/lib64/R/library/modest/Conduct/www/MRC.png
/usr/lib64/R/library/modest/DESCRIPTION
/usr/lib64/R/library/modest/Design/DesignReport.Rnw
/usr/lib64/R/library/modest/Design/app.R
/usr/lib64/R/library/modest/Design/mainDoseEscalation.R
/usr/lib64/R/library/modest/Design/www/MRC.png
/usr/lib64/R/library/modest/INDEX
/usr/lib64/R/library/modest/Meta/Rd.rds
/usr/lib64/R/library/modest/Meta/features.rds
/usr/lib64/R/library/modest/Meta/hsearch.rds
/usr/lib64/R/library/modest/Meta/links.rds
/usr/lib64/R/library/modest/Meta/nsInfo.rds
/usr/lib64/R/library/modest/Meta/package.rds
/usr/lib64/R/library/modest/Meta/vignette.rds
/usr/lib64/R/library/modest/NAMESPACE
/usr/lib64/R/library/modest/NEWS
/usr/lib64/R/library/modest/R/modest
/usr/lib64/R/library/modest/R/modest.rdb
/usr/lib64/R/library/modest/R/modest.rdx
/usr/lib64/R/library/modest/doc/Conduct.R
/usr/lib64/R/library/modest/doc/Conduct.Rmd
/usr/lib64/R/library/modest/doc/Conduct.html
/usr/lib64/R/library/modest/doc/Design.R
/usr/lib64/R/library/modest/doc/Design.Rmd
/usr/lib64/R/library/modest/doc/Design.html
/usr/lib64/R/library/modest/doc/index.html
/usr/lib64/R/library/modest/help/AnIndex
/usr/lib64/R/library/modest/help/aliases.rds
/usr/lib64/R/library/modest/help/modest.rdb
/usr/lib64/R/library/modest/help/modest.rdx
/usr/lib64/R/library/modest/help/paths.rds
/usr/lib64/R/library/modest/html/00Index.html
/usr/lib64/R/library/modest/html/R.css
